
language: r
r: bioc-devel
sudo: true
cache: packages
warnings_are_errors: false
bioc_required: true
bioc_use_devel: true
r_packages:
  - devtools

before_install:
    - Rscript -e 'source(file = "http://bioconductor.org/biocLite.R"); tryCatch(useDevel(devel = TRUE), error = function(err){message(err)})'
    - Rscript -e 'if(!requireNamespace("Gviz", quietly = TRUE)){BiocManager::install("Gviz", version = "3.9"); library("Gviz")}'
# install Gviz from BioC Release 3.5 if BioC Development 3.6 does not work
